name: Count Severity

on:
  workflow_dispatch:


jobs:
  count_severity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Custom Script
        run: |
          chmod +x count_severity.sh
          ./count_severity.sh > result.json
          cat result.json
      - name: Generate HTML Summary
        if: always()
        run: |
           echo "<html><body><table border='1'><thead><tr><th>Severity</th><th>Count</th></tr></thead><tbody>" > $GITHUB_WORKSPACE/summary.html
           cat result.json | jq -r '.SeverityCount[] | "<tr><td>\(.severity)</td><td>\(.count)</td></tr>"' >> $GITHUB_WORKSPACE/summary.html
           echo "</tbody></table>" >> $GITHUB_WORKSPACE/summary.html
           echo "<p>Trafficlight: $(jq -r '.Trafficlight' result.json)</p>" >> $GITHUB_WORKSPACE/summary.html
           echo "</body></html>" >> $GITHUB_WORKSPACE/summary.html
      - name: Display
        run:  cat $GITHUB_WORKSPACE/summary.html >> $GITHUB_STEP_SUMMARY
      - name: Convert HTML to Markdown
        run: |
         cat $GITHUB_WORKSPACE/summary.html |
          pandoc -f html -t markdown -o $GITHUB_WORKSPACE/summary.md
        shell: bash

      - name: Update Pull Request Description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
             const fs = require('fs');
             const summaryMarkdown = fs.readFileSync('./summary.md', 'utf8');

             github.rest.pulls.update({
               owner: context.repo.owner,
               repo: context.repo.repo,
               pull_number: context.issue.number,
               body: context.payload.pull_request.body + `\n\n${summaryMarkdown}`,
             });

